# Generated by Django 3.1.2 on 2020-10-18 06:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=20, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=10, verbose_name='Имя')),
                ('big_name', models.CharField(max_length=20, verbose_name='Отчество')),
                ('text', models.TextField(max_length=100, verbose_name='Описание')),
                ('birth_day', models.DateField(default=datetime.datetime(2020, 10, 18, 12, 3, 35, 874179), verbose_name='Дата рождение')),
                ('num_ber', models.CharField(max_length=20, verbose_name='Номер')),
                ('email', models.EmailField(max_length=30, verbose_name='Gmail')),
                ('social', models.URLField(max_length=30, verbose_name='Соц сети')),
            ],
        ),
    ]
