# Generated by Django 3.1.2 on 2020-10-21 17:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacs',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Люди'},
        ),
        migrations.AlterField(
            model_name='contacs',
            name='birth_day',
            field=models.DateField(default=datetime.datetime(2020, 10, 21, 23, 28, 16, 840543), verbose_name='Дата рождение'),
        ),
    ]
